TARGETS := knn_supervised knn_unsupervised
include ../Makefile.in.icpc
include ../Makefile.common

TO_INSTALL := knn_supervised.cc knn_unsupervised.cc
DIR := knn
ARCH := icpc

knn_supervised: knn_supervised.o
	${LINK} -o knn_supervised knn_supervised.o ${LIBS}

knn_unsupervised: knn_unsupervised.o
	${LINK} -o knn_unsupervised knn_unsupervised.o ${LIBS}
