TARGETS := knn_supervised knn_unsupervised
include ../Makefile.in.x86
include ../Makefile.common

TO_INSTALL := knn_supervised.cc knn_unsupervised.cc
DIR := knn
ARCH := x86

knn_supervised: knn_supervised.o
	${MPICXX} ${CXXFLAGS} -o knn_supervised knn_supervised.o ${LIBS}

knn_unsupervised: knn_unsupervised.o
	${MPICXX} ${CXXFLAGS} -o knn_unsupervised knn_unsupervised.o ${LIBS}
