TARGETS := knn
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := knn.cc
DIR := knn
ARCH := ve

knn: knn.o
	#${LINK} -o knn -ftrace knn.o ${LIBS}
	${LINK} -o knn knn.o ${LIBS}

knn.o:	knn.cc
	#${MPICXX} -c ${CXXFLAGS} -ftrace -report-all $< -o $@
	${MPICXX} -c ${CXXFLAGS} -report-all $< -o $@
