TARGETS := mf
include ../Makefile.in.sx
include ../Makefile.common

TO_INSTALL := mf.cc
DIR := matrixfactorization
ARCH := sx

mf: mf.o
	${CXX} -prelink ${CXXFLAGS} mf.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o mf mf.o ${LIBS}
