TARGETS := cc_BFS sssp pagerank 
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := cc_BFS.cc sssp.cc pagerank.cc
DIR := graph
ARCH := ve


cc_BFS: cc_BFS.o
	${LINK} -o cc_BFS cc_BFS.o ${LIBS}

sssp: sssp.o
	${LINK} -o sssp sssp.o ${LIBS}

pagerank: pagerank.o
	${LINK} -o pagerank pagerank.o ${LIBS}

