.TH "arpack_wrapper" "" "" "" ""
.SH NAME
.PP
arpack_wrapper \- a frovedis module supports singular value
decomposition on sparse data using arpack routines.
.SH SYNOPSIS
.PP
import frovedis.matrix.wrapper.ARPACK
.SS Public Member Functions
.PP
ARPACK.computeSVD (data, k)
.SH DESCRIPTION
.PP
This module provides interface to compute singular value decomposition
on sparse data using arpack native routines at frovedis server side.
.SS Detailed Description
.SS computeSVD (data, k)
.PP
\f[B]Parameters\f[]
.PD 0
.P
.PD
\f[I]data\f[]: Any scipy sparse matrix or python array\-like structure
or an instance of FrovedisCRSMatrix.
.PD 0
.P
.PD
\f[I]k\f[]: An integer value to specify the number of singular values to
compute.
.PP
\f[B]Purpose\f[]
.PD 0
.P
.PD
It computes the singular value decomposition on the sparse data at
frovedis side.
Once done, it returns a GesvdResult object containing the proxy of the
results at frovedis server.
.PP
When required, the spark client can convert back the frovedis server
side SVD result to numpy data by calling to_numpy_results() function on
GesvdResult structure.
.PP
For example,
.IP
.nf
\f[C]
res\ =\ ARPACK.computeSVD(data,2)\ //\ compute\ 2\ singular\ values\ for\ the\ given\ data
p_res\ =\ res.to_numpy_results()\ 
\f[]
.fi
.PP
\f[B]Return Value\f[]
.PD 0
.P
.PD
On success, it returns an object of GesvdResult type containing the
proxy of SVD results at frovedis server side.
If any error occurs, it throws an exception.
