TARGETS := ve_train_word
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := ve_train_word.cc
DIR := word2vec
ARCH := ve

ve_train_word: ve_train_word.o
	${LINK} -fopenmp -mno-create-threads-at-startup -o ve_train_word ve_train_word.o ${LIBS}

