TARGETS := standard_scaler
include ../Makefile.in.icpc
include ../Makefile.common

TO_INSTALL := standard_scaler.cc
DIR := standard_scaler
ARCH := icpc

standard_scaler: standard_scaler.o
	${LINK} -o standard_scaler standard_scaler.o ${LIBS}
