TARGETS := eigen shrink_eigen
include ../Makefile.in.sx
include ../Makefile.common

TO_INSTALL := eigen.cc shrink_eigen.cc
DIR := eigen
ARCH := sx

eigen: eigen.o
	${CXX} -prelink ${CXXFLAGS} eigen.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o eigen eigen.o ${LIBS}

shrink_eigen: shrink_eigen.o
	${CXX} -prelink ${CXXFLAGS} shrink_eigen.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o shrink_eigen shrink_eigen.o ${LIBS}
