TARGETS := agglomerative
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := agglomerative.cc
DIR := agglomerative_newapi
ARCH := ve

agglomerative: agglomerative.o
	${LINK} -o agglomerative agglomerative.o ${LIBS}
