TARGETS := agglomerative
include ../Makefile.in.icpc
include ../Makefile.common

TO_INSTALL := agglomerative.cc
DIR := agglomerative_newapi
ARCH := icpc

agglomerative: agglomerative.o
	${LINK} -o agglomerative agglomerative.o ${LIBS}
