TARGETS := search_cv k_fold
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := search_cv.cc k_fold.cc
DIR := GridSearchCV
ARCH := ve

search_cv: search_cv.o
	${LINK} -o search_cv search_cv.o ${LIBS}

k_fold: k_fold.o
	${LINK} -o k_fold k_fold.o ${LIBS}
