TARGETS := nb
include ../Makefile.in.sx
include ../Makefile.common

TO_INSTALL := nb.cc
DIR := nb
ARCH := sx

nb: nb.o
	${CXX} -prelink ${CXXFLAGS} nb.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o nb nb.o ${LIBS}
