TARGETS := spectral
include ../Makefile.in.icpc
include ../Makefile.common

TO_INSTALL := spectral.cc
DIR := spectral_newapi
ARCH := icpc

spectral: spectral.o
	${LINK} -o spectral spectral.o ${LIBS}
