TARGETS := wikipedia2matrix
include ../Makefile.in.sx
include ../Makefile.common

TO_INSTALL := README sample.txt wikipedia2matrix.cc
DIR := wikipedia2matrix
ARCH := sx

wikipedia2matrix: wikipedia2matrix.o
	${CXX} -prelink ${CXXFLAGS} wikipedia2matrix.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o wikipedia2matrix wikipedia2matrix.o ${LIBS}
