TARGETS := wikipedia2matrix
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := README sample.txt wikipedia2matrix.cc
DIR := wikipedia2matrix
ARCH := ve

wikipedia2matrix: wikipedia2matrix.o
	${LINK} -o wikipedia2matrix wikipedia2matrix.o ${LIBS}
