include ../../../Makefile.in.x86
include Makefile.common

frovedis_server: frovedis_server.o ${OBJS} 
	${MPICXX} ${CXXFLAGS} -o frovedis_server frovedis_server.o ${OBJS} ${LIBS}	

libfrovedis_server.a: ${OBJS}
	${AR} r libfrovedis_server.a ${OBJS}
