include ../../../Makefile.in.icpc
include Makefile.common

frovedis_server: frovedis_server.o model_tracker.o
	${LINK} -o frovedis_server frovedis_server.o model_tracker.o ${LIBS}	

libfrovedis_server.a: ${OBJS}
	${AR} r libfrovedis_server.a ${OBJS}

