TARGETS := kmeans shrink_kmeans
include ../Makefile.in.icpc
include ../Makefile.common

TO_INSTALL := kmeans.cc shrink_kmeans.cc
DIR := kmeans
ARCH := icpc

kmeans: kmeans.o
	${LINK} -o kmeans kmeans.o ${LIBS}

shrink_kmeans: shrink_kmeans.o
	${LINK} -o shrink_kmeans shrink_kmeans.o ${LIBS}

kmeans_jds: kmeans.cc
	icpc `${MPICXX} -showme:compile` -c ${CXXFLAGS} -DKMEANS_JDS kmeans.cc -o kmeans_jds.o
	${LINK} -o kmeans_jds kmeans_jds.o ${LIBS}

