TARGETS := kmeans
include ../Makefile.in.x86
include ../Makefile.common

TO_INSTALL := kmeans.cc
DIR := kmeans
ARCH := x86

kmeans: kmeans.o
	${MPICXX} ${CXXFLAGS} -o kmeans kmeans.o ${LIBS}

kmeans_jds: kmeans.cc
	${MPICXX} -c ${CXXFLAGS} -DKMEANS_JDS kmeans.cc -o kmeans_jds.o
	${MPICXX} ${CXXFLAGS} -o kmeans_jds kmeans_jds.o ${LIBS}

