TARGETS := fp_growth
include ../Makefile.in.icpc
include ../Makefile.common

TO_INSTALL := fp_growth.cc
DIR := fp_growth
ARCH := icpc

fp_growth: fp_growth.o
	${LINK} -o fp_growth fp_growth.o ${LIBS}
