TARGETS := fp_growth
include ../Makefile.in.sx
include ../Makefile.common

TO_INSTALL := fp_growth.cc
DIR := fp_growth
ARCH := sx

fp_growth: fp_growth.o
	${CXX} -prelink ${CXXFLAGS} fp_growth.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o fp_growth fp_growth.o ${LIBS}
