#ifndef ARPACKDEF_HPP
#define ARPACKDEF_HPP
extern "C" {
  void pdsaupd_(int* comm,
                int *ido,
                char *bmat,
                int *nloc,
                char *which,
                int *nev,
                double *tol,
                double *resid,
                int *ncv,
                double *v,
                int *ldv,
                int *iparam,
                int *ipntr,
                double *workd,
                double *workl,
                int *lworkl,
                int *info);
  
  void pdseupd_(int* comm,
                int *rvec,
                char *howmny,
                int *select,
                double *d,
                double *z,
                int *ldz,
                double *sigma,
                char *bmat,
                int *n,
                char *which,
                int *nev,
                double *tol,
                double *resid,
                int *ncv,
                double *v,
                int *ldv,
                int *iparam,
                int *ipntr,
                double *workd,
                double *workl,
                int *lworkl,
                int *info);  

  void pssaupd_(int* comm,
                int *ido,
                char *bmat,
                int *nloc,
                char *which,
                int *nev,
                float *tol,
                float *resid,
                int *ncv,
                float *v,
                int *ldv,
                int *iparam,
                int *ipntr,
                float *workd,
                float *workl,
                int *lworkl,
                int *info);
  
  void psseupd_(int* comm,
                int *rvec,
                char *howmny,
                int *select,
                float *d,
                float *z,
                int *ldz,
                float *sigma,
                char *bmat,
                int *n,
                char *which,
                int *nev,
                float *tol,
                float *resid,
                int *ncv,
                float *v,
                int *ldv,
                int *iparam,
                int *ipntr,
                float *workd,
                float *workl,
                int *lworkl,
                int *info);  
}

template <class REAL>
void pxsaupd(int* comm,
             int *ido,
             char *bmat,
             int *nloc,
             char *which,
             int *nev,
             REAL *tol,
             REAL *resid,
             int *ncv,
             REAL *v,
             int *ldv,
             int *iparam,
             int *ipntr,
             REAL *workd,
             REAL *workl,
             int *lworkl,
             int *info);

template <>
void pxsaupd<double>(int* comm,
                     int *ido,
                     char *bmat,
                     int *nloc,
                     char *which,
                     int *nev,
                     double *tol,
                     double *resid,
                     int *ncv,
                     double *v,
                     int *ldv,
                     int *iparam,
                     int *ipntr,
                     double *workd,
                     double *workl,
                     int *lworkl,
                     int *info);

template <>
void pxsaupd<float>(int* comm,
                    int *ido,
                    char *bmat,
                    int *nloc,
                    char *which,
                    int *nev,
                    float *tol,
                    float *resid,
                    int *ncv,
                    float *v,
                    int *ldv,
                    int *iparam,
                    int *ipntr,
                    float *workd,
                    float *workl,
                    int *lworkl,
                    int *info);

template <class REAL>
void pxseupd(int* comm,
             int *rvec,
             char *howmny,
             int *select,
             REAL *d,
             REAL *z,
             int *ldz,
             REAL *sigma,
             char *bmat,
             int *n,
             char *which,
             int *nev,
             REAL *tol,
             REAL *resid,
             int *ncv,
             REAL *v,
             int *ldv,
             int *iparam,
             int *ipntr,
             REAL *workd,
             REAL *workl,
             int *lworkl,
             int *info);  

template <>
void pxseupd<double>(int* comm,
                     int *rvec,
                     char *howmny,
                     int *select,
                     double *d,
                     double *z,
                     int *ldz,
                     double *sigma,
                     char *bmat,
                     int *n,
                     char *which,
                     int *nev,
                     double *tol,
                     double *resid,
                     int *ncv,
                     double *v,
                     int *ldv,
                     int *iparam,
                     int *ipntr,
                     double *workd,
                     double *workl,
                     int *lworkl,
                     int *info);

template <>
void pxseupd<float>(int* comm,
                    int *rvec,
                    char *howmny,
                    int *select,
                    float *d,
                    float *z,
                    int *ldz,
                    float *sigma,
                    char *bmat,
                    int *n,
                    char *which,
                    int *nev,
                    float *tol,
                    float *resid,
                    int *ncv,
                    float *v,
                    int *ldv,
                    int *iparam,
                    int *ipntr,
                    float *workd,
                    float *workl,
                    int *lworkl,
                    int *info);

#endif
