TARGETS := train_classifier train_regressor dump prune predict
DEPENDS := ${TARGETS:%=%.d}

include ../Makefile.in.sx
include ../Makefile.common
-include ${DEPENDS}

TO_INSTALL := ${TARGETS:%=%.cc}
DIR := tree
ARCH := sx

${TARGETS}: %: %.o
	${CXX} -prelink ${CXXFLAGS} $^ ${LIBS}
	${MPICXX} ${CXXFLAGS} -o $@ $^ ${LIBS}
