TARGETS := train_classifier train_regressor dump prune predict
DEPENDS := ${TARGETS:%=%.d}

include ../Makefile.in.x86
include ../Makefile.common
-include ${DEPENDS}

TO_INSTALL := ${TARGETS:%=%.cc}
DIR := tree
ARCH := x86

${TARGETS}: %: %.o
	${MPICXX} ${CXXFLAGS} -o $@ $^ ${LIBS}
