TARGETS := train_classifier train_regressor dump prune predict
DEPENDS := ${TARGETS:%=%.d}

include ../Makefile.in.icpc
include ../Makefile.common
-include ${DEPENDS}

TO_INSTALL := ${TARGETS:%=%.cc}
DIR := tree
ARCH := icpc

${TARGETS}: %: %.o
	${LINK} -o $@ $^ ${LIBS}
