include ../../../Makefile.in.x86
include Makefile.common

w2v_core.o: w2v_core.cc 
	${MPICXX} -c ${CXXFLAGS} -fopenmp $< -o $@	
CC := gcc


libfrovedis_ml.a: ${OBJS}
	${AR} r libfrovedis_ml.a ${OBJS}
