include ../../../Makefile.in.sx
include Makefile.common

word2vec.o: word2vec.cc
	${RM} $(@:.o=.ir) $(@:.o=.ti) $@
	${MPICXX} -c ${CXXFLAGS} -Popenmp $< -o $@

libfrovedis_ml.a: ${OBJS}
	${CXX} -prelink ${OBJS} -L../matrix -lfrovedis_matrix -L../core -lfrovedis_core ${LIBS_COMMON}
	${AR} r libfrovedis_ml.a ${OBJS}
