TARGETS := train_fm test_fm
include ../Makefile.in.sx
include ../Makefile.common

TO_INSTALL := train_fm.cc test_fm.cc
DIR := factorization_machine
ARCH := sx

train_fm: train_fm.o
	${CXX} -prelink ${CXXFLAGS} train_fm.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o train_fm train_fm.o ${LIBS}

test_fm: test_fm.o
	${CXX} -prelink ${CXXFLAGS} test_fm.o ${LIBS}
	${MPICXX} ${CXXFLAGS} -o test_fm test_fm.o ${LIBS}

