TARGETS := vecop matop
include ../Makefile.in.ve
include ../Makefile.common

TO_INSTALL := vecop.cc matop.cc
DIR := vector_matrix_operations
ARCH := ve

vecop: vecop.o
	${LINK} -o vecop vecop.o ${LIBS}

matop: matop.o
	${LINK} -o matop matop.o ${LIBS}
